### ISSUE TITLE
The `/cluster-inspect` view is blank when selecting a cluster

### ISSUE THREAD

**Issue by thomasvn** [kubecost/features-bugs#14]
## Describe the bug

When going to `/cluster-inspect`, I'm met with a blank page. Upon inspecting the API requests the frontend is making to the backend, this one is consistently failing with HTTP 500 `/model/savings/clusterSizingETL`.

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/11251627/80b4e7a0-87f5-4667-ac9d-e261182f8dc7)

## Reproduce

1. Go to the `/overview` page.
2. Click on an active cluster under `Cluster breakdown`
3. Get redirected to `/cluster-inspect`, sometimes failing

HAR files with reproduced behavior linked in Slack thread below.

## Expected behavior

Identify all locations in the frontend that are calling `/model/savings/clusterSizingETL`. Build a graceful failure mode so that the frontend doesn't retry the request too many times, and doesn't end up displaying a blank page.

## Please share the support case, if any

Link to a [Slack thread](https://kubecost.slack.com/archives/G01MN4R06MB/p1685659802321319) showing that at least four users are running into this issue.

## What impact will this have on your ability to get value out of Kubecost?

My team has enjoyed using the `/cluster-inspect` view, as it concisely summarizes all the activity on the cluster. Being unable to use it now disrupts our workflow.

**Comment by jessegoodier** [comment]
@kwombach12 @teevans 
FYI, good issue for bug week. This page has been problematic for some time.

**Comment by teevans** [comment]
@nealormsbee for visibility - But I believe we made some improvements here.

**Comment by kwombach12** [comment]
Thanks @thomasvn I have logged a ticket for us to look at this in 105

**Comment by nealormsbee** [comment]
@aligon just merged/picked a patch for this issue -- should be resolved in 1.104.

**Comment by thomasvn** [comment]
Speed! Thanks for the work here @aligon @nealormsbee.

I see that there's a graceful failure added for the `cluster-inspect` page. Any thoughts on doing this same error handling across all locations where we call `/model/savings/clusterSizingETL`?

**Comment by nealormsbee** [comment]
Well really we should have graceful error handling for all our API calls 😅

**Comment by jgarcia-pluralsight** [comment]
This is still an issue for me and I'm on the latest release, 1.106.2

**Comment by chipzoller** [comment]
Transferred to the features-bugs repo since this is an application-level issue and not a Helm chart one.

**Comment by kwombach12** [comment]
@jgarcia-pluralsight this appears to be fixed in our 1.104 release. Can you share some more context so we can try to repro?

**Comment by jgarcia-pluralsight** [comment]
Just like the original post, when I click the Monitor -> Cluster it just shows this error message: 
![image](https://github.com/kubecost/features-bugs/assets/92823067/462ac4a6-ee34-449d-9d99-a9556e09ae74)

I've attached the HAR file as well. I expect a report page with data to populate instead of the error message.
[Harfile.zip](https://github.com/kubecost/features-bugs/files/12917892/Harfile.zip)

**Comment by kwombach12** [comment]
@jcharcalla Can you take a look here? The cluster inspect page is working for me in the environments I have setup.

**Comment by jgarcia-pluralsight** [comment]
Here's an image of my chart version: 
![image](https://github.com/kubecost/features-bugs/assets/92823067/411719d1-b0cc-4f30-81ce-2971cbf224fd)

**Comment by jessegoodier** [comment]
@jgarcia-pluralsight Do you mind sharing your helm values with me? Perhaps here or via slack DM?
https://kubecost.com/join-slack

**Comment by nealormsbee** [comment]
From the HAR file, it looks like the install is behind an ingress, but we're sending some requests to `/model/*` instead of `/kubecost/model/*`. So I think some parts of that page are just determining the basepath incorrectly. This was an issue in the past that I thought we had resolved.

EDIT: By "behind an ingress" I mean an ingress that hosts the Kubecost application at a subpath. So all of the API call should be prefixed with a `/kubecost` path.

**Comment by jessegoodier** [comment]
Neal is correct. added BURNDOWN-244

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
